# Generated by Django 2.2 on 2023-11-23 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacionesweb_api', '0006_auto_20231123_0422'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profiles',
            name='matricula',
        ),
    ]
